In [1]:
import pandas as pd

In [2]:
mental=pd.read_csv("Student Mental health.csv")

In [3]:
#checks for empty cells
mental.isnull().sum()

Timestamp                                       0
Choose your gender                              0
Age                                             1
What is your course?                            0
Your current year of Study                      0
What is your CGPA?                              0
Marital status                                  0
Do you have Depression?                         0
Do you have Anxiety?                            0
Do you have Panic attack?                       0
Did you seek any specialist for a treatment?    0
dtype: int64

In [4]:
mental

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...
96,13/07/2020 19:56:49,Female,21.0,BCS,year 1,3.50 - 4.00,No,No,Yes,No,No
97,13/07/2020 21:21:42,Male,18.0,Engineering,Year 2,3.00 - 3.49,No,Yes,Yes,No,No
98,13/07/2020 21:22:56,Female,19.0,Nursing,Year 3,3.50 - 4.00,Yes,Yes,No,Yes,No
99,13/07/2020 21:23:57,Female,23.0,Pendidikan Islam,year 4,3.50 - 4.00,No,No,No,No,No
100,18/07/2020 20:16:21,Male,20.0,Biomedical science,Year 2,3.00 - 3.49,No,No,No,No,No

In [5]:
mental["What is your CGPA?"].unique()

array(['3.00 - 3.49', '3.50 - 4.00', '3.50 - 4.00 ', '2.50 - 2.99',
       '2.00 - 2.49', '0 - 1.99'], dtype=object)

# fill na

In [6]:
#fill the empty cells to remove the empty
mental.fillna(0)
# ASSIGN IT BACK TO THE DATAFRAME
mental=mental.fillna(0)

# CONVERT ALL  CATEGORICAL COLUMNS TO NUMERICAL COLUMNS

In [7]:
mental["What is your CGPA?"].unique()
#there is an error to values of same value.
#one has to be removed either converting to string first then float

array(['3.00 - 3.49', '3.50 - 4.00', '3.50 - 4.00 ', '2.50 - 2.99',
       '2.00 - 2.49', '0 - 1.99'], dtype=object)

In [8]:
mental["What is your CGPA?"].dtype
#no need to convert to string now to remove using strip

dtype('O')

In [9]:
mental["What is your CGPA?"]=mental["What is your CGPA?"].str.strip()
#now the empty spaces have been removed correcting the erroe of duplicates

In [10]:
mental["What is your CGPA?"].unique()

array(['3.00 - 3.49', '3.50 - 4.00', '2.50 - 2.99', '2.00 - 2.49',
       '0 - 1.99'], dtype=object)

In [11]:
pd.set_option("display.max_rows",None)

In [12]:
#3.00 - 3.49 - 1
#3.50 - 4.00 - 2
#3.50 - 4.00 - 3
#2.50 - 2.99 -4
#2.00 - 2.49 - 5
# 0 - 1.99 - 6
#the numbers in are seen as objects
mental["What is your CGPA?"].map({"3.00 - 3.49":2,"3.50 - 4.00":1,"2.50 - 2.99":3,"2.00 - 2.49":4,"0 - 1.99":5 })

mental["What is your CGPA?"]=mental["What is your CGPA?"].map({"3.00 - 3.49":2,"3.50 - 4.00":1,"2.50 - 2.99":3,"2.00 - 2.49":4,"0 - 1.99":5 })

In [13]:
#convert your cgpa column to integer column using
#.ASTYPE

In [14]:
mental["What is your CGPA?"].unique()
#to check if they are correct

array([2, 1, 3, 4, 5], dtype=int64)

In [15]:
mental["What is your CGPA?"].astype(int)
# to convert it to integer to enable mapping

0      2
1      2
2      2
3      2
4      2
5      1
6      1
7      1
8      3
9      1
10     1
11     1
12     2
13     2
14     1
15     1
16     2
17     2
18     1
19     1
20     2
21     2
22     1
23     2
24     1
25     1
26     1
27     2
28     1
29     1
30     2
31     2
32     1
33     1
34     2
35     4
36     2
37     3
38     1
39     3
40     2
41     1
42     2
43     5
44     1
45     1
46     1
47     1
48     2
49     1
50     3
51     1
52     2
53     2
54     1
55     2
56     1
57     2
58     1
59     2
60     2
61     1
62     1
63     1
64     1
65     1
66     2
67     2
68     1
69     2
70     2
71     1
72     2
73     5
74     1
75     1
76     2
77     2
78     5
79     1
80     1
81     1
82     2
83     2
84     2
85     1
86     2
87     1
88     2
89     4
90     1
91     2
92     2
93     2
94     5
95     1
96     1
97     2
98     1
99     1
100    2
Name: What is your CGPA?, dtype: int32

In [16]:
mental

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,2,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,2,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,2,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,2,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,2,No,No,No,No,No
5,8/7/2020 12:31,Male,19.0,Engineering,Year 2,1,No,No,No,Yes,No
6,8/7/2020 12:32,Female,23.0,Pendidikan islam,year 2,1,Yes,Yes,No,Yes,No
7,8/7/2020 12:33,Female,18.0,BCS,year 1,1,No,No,Yes,No,No
8,8/7/2020 12:35,Female,19.0,Human Resources,Year 2,3,No,No,No,No,No
9,8/7/2020 12:39,Male,18.0,Irkhs,year 1,1,No,No,Yes,Yes,No
10,8/7/2020 12:39,Female,20.0,Psychology,year 1,1,No,No,No,No,No
11,8/7/2020 12:39,Female,24.0,Engineering,Year 3,1,Yes,Yes,No,No,No
12,8/7/2020 12:40,Female,18.0,BCS,year 1,2,No,Yes,No,No,No
13,8/7/2020 12:41,Male,19.0,Engineering,year 1,2,No,No,No,No,No
14,8/7/2020 12:43,Female,18.0,KENMS,Year 2,1,No,No,Yes,No,No
15,8/7/2020 12:43,Male,24.0,BCS,Year 3,1,No,No,No,No,No
16,8/7/2020 12:46,Female,24.0,Accounting,year 3,2,No,No,No,No,No
17,8/7/2020 12:52,Female,24.0,ENM,year 4,2,Yes,Yes,Yes,Yes,No
18,8/7/2020 13:05,Female,20.0,BIT,Year 2,1,No,No,Yes,No,No
19,8/7/2020 13:07,Female,18.0,Marine science,year 2,1,Yes,Yes,Yes,Yes,No
20,8/7/2020 13:12,Female,19.0,Engineering,year 1,2,No,No,No,Yes,No
21,8/7/2020 13:13,Female,18.0,KOE,Year 2,2,No,No,No,No,No
22,8/7/2020 13:13,Female,24.0,BCS,year 1,1,No,No,No,No,No
23,8/7/2020 13:15,Female,24.0,Engineering,year 1,2,No,No,No,No,No
24,8/7/2020 13:17,Female,23.0,BCS,Year 3,1,No,Yes,Yes,Yes,No
25,8/7/2020 13:29,Female,18.0,Banking Studies,year 1,1,No,No,No,No,No
26,8/7/2020 13:35,Female,19.0,Engineering,year 1,1,No,No,No,No,No
27,8/7/2020 13:41,Male,18.0,Engineering,Year 2,2,Yes,Yes,Yes,No,No
28,8/7/2020 13:58,Female,24.0,BIT,Year 3,1,Yes,Yes,Yes,Yes,Yes
29,8/7/2020 14:05,Female,24.0,BCS,year 4,1,No,No,No,No,No
30,8/7/2020 14:27,Female,23.0,Business Administration,Year 2,2,No,No,No,No,No
31,8/7/2020 14:29,Male,18.0,BCS,year 2,2,No,No,No,No,No
32,8/7/2020 14:29,Male,19.0,BCS,year 1,1,No,No,No,Yes,No
33,8/7/2020 14:31,Male,18.0,BCS,Year 2,1,Yes,Yes,Yes,No,Yes
34,8/7/2020 14:41,Female,19.0,BIT,year 1,2,No,Yes,Yes,Yes,No
35,8/7/2020 14:43,Female,18.0,Engineering,year 1,4,No,No,No,No,No
36,8/7/2020 14:43,Female,18.0,Law,Year 3,2,No,Yes,Yes,No,No
37,8/7/2020 14:45,Female,19.0,BIT,year 1,3,No,Yes,Yes,Yes,No
38,8/7/2020 14:47,Female,18.0,KIRKHS,year 1,1,No,No,No,No,No
39,8/7/2020 14:56,Female,24.0,Engineering,Year 2,3,Yes,Yes,No,Yes,Yes
40,8/7/2020 14:57,Female,24.0,BIT,Year 3,2,No,No,Yes,No,No
41,8/7/2020 14:57,Female,22.0,Engineering,year 4,1,No,No,No,No,No
42,8/7/2020 14:58,Female,20.0,Usuluddin,year 2,2,No,Yes,No,No,No
43,8/7/2020 15:07,Male,0.0,BIT,year 1,5,No,No,No,No,No
44,8/7/2020 15:08,Male,23.0,TAASL,year 2,1,No,No,No,Yes,No
45,8/7/2020 15:09,Male,18.0,BCS,year 1,1,No,No,Yes,Yes,No
46,8/7/2020 15:12,Female,19.0,Engineering,year 1,1,No,No,Yes,No,No
47,8/7/2020 15:14,Female,18.0,Engine,year 4,1,No,No,No,No,No
48,8/7/2020 15:14,Male,24.0,BCS,year 2,2,No,Yes,No,No,No
49,8/7/2020 15:18,Female,24.0,BCS,year 3,1,No,No,No,Yes,No
50,8/7/2020 15:27,Female,23.0,ALA,year 1,3,Yes,Yes,No,Yes,Yes
51,8/7/2020 15:37,Female,18.0,BCS,year 2,1,No,No,Yes,No,No
52,8/7/2020 15:47,Female,19.0,Biomedical science,year 3,2,No,No,No,No,No
53,8/7/2020 15:48,Female,20.0,koe,year 3,2,Yes,Yes,Yes,Yes,No
54,8/7/2020 15:57,Female,19.0,BCS,year 1,1,No,Yes,No,Yes,Yes
55,8/7/2020 15:58,Male,21.0,BCS,year 1,2,No,No,No,No,No
56,8/7/2020 16:08,Male,23.0,Kirkhs,Year 3,1,No,No,No,No,No
57,8/7/2020 16:21,Female,20.0,BENL,Year 3,2,No,Yes,Yes,No,No
58,8/7/2020 16:22,Female,18.0,BCS,year 1,1,No,No,No,No,No
59,8/7/2020 16:34,Female,23.0,Benl,year 1,2,No,No,No,No,No
60,8/7/2020 16:34,Female,18.0,IT,Year 3,2,No,No,No,Yes,No
61,8/7/2020 16:53,Female,19.0,BCS,year 1,1,No,No,No,No,No
62,8/7/2020 17:05,Female,18.0,CTS,Year 1,1,No,No,No,Yes,No
63,8/7/2020 17:37,Female,24.0,engin,year 1,1,No,No,No,Yes,No
64,8/7/2020 17:46,Female,24.0,Engine,year 1,1,No,No,No,No,No
65,8/7/2020 17:50,Female,23.0,Econs,year 1,1,No,Yes,Yes,No,No
66,8/7/2020 18:10,Female,18.0,KOE,Year 3,2,No,No,Yes,No,No
67,8/7/2020 18:11,Male,19.0,MHSC,Year 3,2,Yes,Yes,No,Yes,No
68,8/7/2020 19:05,Female,18.0,Malcom,year 1,1,No,Yes,No,No,No
69,8/7/2020 19:32,Female,24.0,Kop,year 4,2,No,No,Yes,No,No
70,8/7/2020 20:36,Female,24.0,Biomedical science,year 1,2,No,No,No,No,No
71,8/7/2020 21:21,Female,18.0,Laws,Year 3,1,No,No,No,Yes,No
72,8/7/2020 22:35,Female,19.0,BIT,Year 3,2,Yes,Yes,No,No,No
73,9/7/2020 6:57,Male,18.0,Biomedical science,year 1,5,No,No,No,No,No
74,9/7/2020 11:43,Male,24.0,BIT,Year 3,1,No,No,Yes,No,No
75,9/7/2020 11:57,Female,24.0,KOE,year 1,1,No,No,Yes,Yes,No
76,9/7/2020 13:15,Female,23.0,Engineering,year 1,2,No,Yes,No,No,No
77,9/7/2020 18:24,Female,18.0,Human Sciences,Year 2,2,No,No,No,Yes,No
78,13/07/2020 10:07:32,Female,19.0,Biotechnology,Year 3,5,No,No,No,No,No
79,13/07/2020 10:10:30,Female,18.0,Engineering,year 4,1,No,No,No,No,No
80,13/07/2020 10:11:26,Female,24.0,Communication,Year 2,1,Yes,Yes,Yes,Yes,No
81,13/07/2020 10:12:18,Female,24.0,Diploma Nursing,year 2,1,No,No,No,No,No
82,13/07/2020 10:12:26,Female,19.0,Engineering,year 1,2,No,Yes,Yes,No,No
83,13/07/2020 10:12:28,Female,19.0,Pendidikan Islam,Year 2,2,No,No,No,No,No
84,13/07/2020 10:14:46,Male,23.0,Radiography,year 1,2,No,No,No,No,No
85,13/07/2020 10:33:47,Female,18.0,psychology,year 1,1,No,Yes,Yes,No,Yes
86,13/07/2020 10:34:08,Female,19.0,Fiqh fatwa,Year 3,2,No,No,No,No,No
87,13/07/2020 11:46:13,Female,18.0,psychology,year 1,1,No,Yes,Yes,Yes,No
88,13/07/2020 11:49:02,Male,24.0,BIT,year 1,2,No,No,Yes,No,No
89,13/07/2020 11:54:58,Male,24.0,Engineering,Year 2,4,No,No,No,Yes,No
90,13/07/2020 13:57:11,Female,23.0,DIPLOMA TESL,Year 3,1,No,No,No,Yes,No
91,13/07/2020 14:38:12,Male,18.0,Koe,Year 2,2,No,No,Yes,No,No
92,13/07/2020 14:48:05,Female,19.0,KOE,year 2,2,Yes,Yes,No,No,No
93,13/07/2020 16:15:13,Female,18.0,BENL,year 1,2,No,Yes,No,No,No
94,13/07/2020 17:30:44,Female,24.0,Fiqh,Year 3,5,No,No,No,Yes,No
95,13/07/2020 19:08:32,Female,18.0,Islamic Education,year 1,1,No,No,No,No,No
96,13/07/2020 19:56:49,Female,21.0,BCS,year 1,1,No,No,Yes,No,No
97,13/07/2020 21:21:42,Male,18.0,Engineering,Year 2,2,No,Yes,Yes,No,No
98,13/07/2020 21:22:56,Female,19.0,Nursing,Year 3,1,Yes,Yes,No,Yes,No
99,13/07/2020 21:23:57,Female,23.0,Pendidikan Islam,year 4,1,No,No,No,No,No
100,18/07/2020 20:16:21,Male,20.0,Biomedical science,Year 2,2,No,No,No,No,No

In [17]:
mental["Marital status"].astype(str)
mental["Marital status"].map({"NO":0,"YES":1})
mental["Marital status"]=mental["Marital status"].map({"No":0,"Yes":1})

In [18]:
mental["Do you have Depression?"].astype(str)
mental["Do you have Depression?"].map({"No":0,"Yes":1})
mental["Do you have Depression?"]=mental["Do you have Depression?"].map({"No":0,"Yes":1})

In [19]:
mental["Do you have Anxiety?"].astype(str)
mental["Do you have Anxiety?"].map({"No":0,"Yes":1})
mental["Do you have Anxiety?"]=mental["Do you have Anxiety?"].map({"No":0,"Yes":1})

In [20]:
mental["Did you seek any specialist for a treatment?"].astype(str)
mental["Did you seek any specialist for a treatment?"].map({"No":0,"Yes":1})
mental["Did you seek any specialist for a treatment?"]=mental["Did you seek any specialist for a treatment?"].map({"No":0,"Yes":1})

In [21]:
mental["Choose your gender"].map({"No":0,"Yes":1})
mental["Choose your gender"]=mental["Choose your gender"].map({"Female":0,"Male":1})

In [22]:
mental

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,0,18.0,Engineering,year 1,2,0,1,0,Yes,0
1,8/7/2020 12:04,1,21.0,Islamic education,year 2,2,0,0,1,No,0
2,8/7/2020 12:05,1,19.0,BIT,Year 1,2,0,1,1,Yes,0
3,8/7/2020 12:06,0,22.0,Laws,year 3,2,1,1,0,No,0
4,8/7/2020 12:13,1,23.0,Mathemathics,year 4,2,0,0,0,No,0
5,8/7/2020 12:31,1,19.0,Engineering,Year 2,1,0,0,0,Yes,0
6,8/7/2020 12:32,0,23.0,Pendidikan islam,year 2,1,1,1,0,Yes,0
7,8/7/2020 12:33,0,18.0,BCS,year 1,1,0,0,1,No,0
8,8/7/2020 12:35,0,19.0,Human Resources,Year 2,3,0,0,0,No,0
9,8/7/2020 12:39,1,18.0,Irkhs,year 1,1,0,0,1,Yes,0
10,8/7/2020 12:39,0,20.0,Psychology,year 1,1,0,0,0,No,0
11,8/7/2020 12:39,0,24.0,Engineering,Year 3,1,1,1,0,No,0
12,8/7/2020 12:40,0,18.0,BCS,year 1,2,0,1,0,No,0
13,8/7/2020 12:41,1,19.0,Engineering,year 1,2,0,0,0,No,0
14,8/7/2020 12:43,0,18.0,KENMS,Year 2,1,0,0,1,No,0
15,8/7/2020 12:43,1,24.0,BCS,Year 3,1,0,0,0,No,0
16,8/7/2020 12:46,0,24.0,Accounting,year 3,2,0,0,0,No,0
17,8/7/2020 12:52,0,24.0,ENM,year 4,2,1,1,1,Yes,0
18,8/7/2020 13:05,0,20.0,BIT,Year 2,1,0,0,1,No,0
19,8/7/2020 13:07,0,18.0,Marine science,year 2,1,1,1,1,Yes,0
20,8/7/2020 13:12,0,19.0,Engineering,year 1,2,0,0,0,Yes,0
21,8/7/2020 13:13,0,18.0,KOE,Year 2,2,0,0,0,No,0
22,8/7/2020 13:13,0,24.0,BCS,year 1,1,0,0,0,No,0
23,8/7/2020 13:15,0,24.0,Engineering,year 1,2,0,0,0,No,0
24,8/7/2020 13:17,0,23.0,BCS,Year 3,1,0,1,1,Yes,0
25,8/7/2020 13:29,0,18.0,Banking Studies,year 1,1,0,0,0,No,0
26,8/7/2020 13:35,0,19.0,Engineering,year 1,1,0,0,0,No,0
27,8/7/2020 13:41,1,18.0,Engineering,Year 2,2,1,1,1,No,0
28,8/7/2020 13:58,0,24.0,BIT,Year 3,1,1,1,1,Yes,1
29,8/7/2020 14:05,0,24.0,BCS,year 4,1,0,0,0,No,0
30,8/7/2020 14:27,0,23.0,Business Administration,Year 2,2,0,0,0,No,0
31,8/7/2020 14:29,1,18.0,BCS,year 2,2,0,0,0,No,0
32,8/7/2020 14:29,1,19.0,BCS,year 1,1,0,0,0,Yes,0
33,8/7/2020 14:31,1,18.0,BCS,Year 2,1,1,1,1,No,1
34,8/7/2020 14:41,0,19.0,BIT,year 1,2,0,1,1,Yes,0
35,8/7/2020 14:43,0,18.0,Engineering,year 1,4,0,0,0,No,0
36,8/7/2020 14:43,0,18.0,Law,Year 3,2,0,1,1,No,0
37,8/7/2020 14:45,0,19.0,BIT,year 1,3,0,1,1,Yes,0
38,8/7/2020 14:47,0,18.0,KIRKHS,year 1,1,0,0,0,No,0
39,8/7/2020 14:56,0,24.0,Engineering,Year 2,3,1,1,0,Yes,1
40,8/7/2020 14:57,0,24.0,BIT,Year 3,2,0,0,1,No,0
41,8/7/2020 14:57,0,22.0,Engineering,year 4,1,0,0,0,No,0
42,8/7/2020 14:58,0,20.0,Usuluddin,year 2,2,0,1,0,No,0
43,8/7/2020 15:07,1,0.0,BIT,year 1,5,0,0,0,No,0
44,8/7/2020 15:08,1,23.0,TAASL,year 2,1,0,0,0,Yes,0
45,8/7/2020 15:09,1,18.0,BCS,year 1,1,0,0,1,Yes,0
46,8/7/2020 15:12,0,19.0,Engineering,year 1,1,0,0,1,No,0
47,8/7/2020 15:14,0,18.0,Engine,year 4,1,0,0,0,No,0
48,8/7/2020 15:14,1,24.0,BCS,year 2,2,0,1,0,No,0
49,8/7/2020 15:18,0,24.0,BCS,year 3,1,0,0,0,Yes,0
50,8/7/2020 15:27,0,23.0,ALA,year 1,3,1,1,0,Yes,1
51,8/7/2020 15:37,0,18.0,BCS,year 2,1,0,0,1,No,0
52,8/7/2020 15:47,0,19.0,Biomedical science,year 3,2,0,0,0,No,0
53,8/7/2020 15:48,0,20.0,koe,year 3,2,1,1,1,Yes,0
54,8/7/2020 15:57,0,19.0,BCS,year 1,1,0,1,0,Yes,1
55,8/7/2020 15:58,1,21.0,BCS,year 1,2,0,0,0,No,0
56,8/7/2020 16:08,1,23.0,Kirkhs,Year 3,1,0,0,0,No,0
57,8/7/2020 16:21,0,20.0,BENL,Year 3,2,0,1,1,No,0
58,8/7/2020 16:22,0,18.0,BCS,year 1,1,0,0,0,No,0
59,8/7/2020 16:34,0,23.0,Benl,year 1,2,0,0,0,No,0
60,8/7/2020 16:34,0,18.0,IT,Year 3,2,0,0,0,Yes,0
61,8/7/2020 16:53,0,19.0,BCS,year 1,1,0,0,0,No,0
62,8/7/2020 17:05,0,18.0,CTS,Year 1,1,0,0,0,Yes,0
63,8/7/2020 17:37,0,24.0,engin,year 1,1,0,0,0,Yes,0
64,8/7/2020 17:46,0,24.0,Engine,year 1,1,0,0,0,No,0
65,8/7/2020 17:50,0,23.0,Econs,year 1,1,0,1,1,No,0
66,8/7/2020 18:10,0,18.0,KOE,Year 3,2,0,0,1,No,0
67,8/7/2020 18:11,1,19.0,MHSC,Year 3,2,1,1,0,Yes,0
68,8/7/2020 19:05,0,18.0,Malcom,year 1,1,0,1,0,No,0
69,8/7/2020 19:32,0,24.0,Kop,year 4,2,0,0,1,No,0
70,8/7/2020 20:36,0,24.0,Biomedical science,year 1,2,0,0,0,No,0
71,8/7/2020 21:21,0,18.0,Laws,Year 3,1,0,0,0,Yes,0
72,8/7/2020 22:35,0,19.0,BIT,Year 3,2,1,1,0,No,0
73,9/7/2020 6:57,1,18.0,Biomedical science,year 1,5,0,0,0,No,0
74,9/7/2020 11:43,1,24.0,BIT,Year 3,1,0,0,1,No,0
75,9/7/2020 11:57,0,24.0,KOE,year 1,1,0,0,1,Yes,0
76,9/7/2020 13:15,0,23.0,Engineering,year 1,2,0,1,0,No,0
77,9/7/2020 18:24,0,18.0,Human Sciences,Year 2,2,0,0,0,Yes,0
78,13/07/2020 10:07:32,0,19.0,Biotechnology,Year 3,5,0,0,0,No,0
79,13/07/2020 10:10:30,0,18.0,Engineering,year 4,1,0,0,0,No,0
80,13/07/2020 10:11:26,0,24.0,Communication,Year 2,1,1,1,1,Yes,0
81,13/07/2020 10:12:18,0,24.0,Diploma Nursing,year 2,1,0,0,0,No,0
82,13/07/2020 10:12:26,0,19.0,Engineering,year 1,2,0,1,1,No,0
83,13/07/2020 10:12:28,0,19.0,Pendidikan Islam,Year 2,2,0,0,0,No,0
84,13/07/2020 10:14:46,1,23.0,Radiography,year 1,2,0,0,0,No,0
85,13/07/2020 10:33:47,0,18.0,psychology,year 1,1,0,1,1,No,1
86,13/07/2020 10:34:08,0,19.0,Fiqh fatwa,Year 3,2,0,0,0,No,0
87,13/07/2020 11:46:13,0,18.0,psychology,year 1,1,0,1,1,Yes,0
88,13/07/2020 11:49:02,1,24.0,BIT,year 1,2,0,0,1,No,0
89,13/07/2020 11:54:58,1,24.0,Engineering,Year 2,4,0,0,0,Yes,0
90,13/07/2020 13:57:11,0,23.0,DIPLOMA TESL,Year 3,1,0,0,0,Yes,0
91,13/07/2020 14:38:12,1,18.0,Koe,Year 2,2,0,0,1,No,0
92,13/07/2020 14:48:05,0,19.0,KOE,year 2,2,1,1,0,No,0
93,13/07/2020 16:15:13,0,18.0,BENL,year 1,2,0,1,0,No,0
94,13/07/2020 17:30:44,0,24.0,Fiqh,Year 3,5,0,0,0,Yes,0
95,13/07/2020 19:08:32,0,18.0,Islamic Education,year 1,1,0,0,0,No,0
96,13/07/2020 19:56:49,0,21.0,BCS,year 1,1,0,0,1,No,0
97,13/07/2020 21:21:42,1,18.0,Engineering,Year 2,2,0,1,1,No,0
98,13/07/2020 21:22:56,0,19.0,Nursing,Year 3,1,1,1,0,Yes,0
99,13/07/2020 21:23:57,0,23.0,Pendidikan Islam,year 4,1,0,0,0,No,0
100,18/07/2020 20:16:21,1,20.0,Biomedical science,Year 2,2,0,0,0,No,0

In [23]:
mental["Do you have Panic attack?"].astype(str)
mental["Do you have Panic attack?"].map({"No":0,"Yes":1})
mental["Do you have Panic attack?"]=mental["Do you have Panic attack?"].map({"No":0,"Yes":1})

In [24]:
mental

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,0,18.0,Engineering,year 1,2,0,1,0,1,0
1,8/7/2020 12:04,1,21.0,Islamic education,year 2,2,0,0,1,0,0
2,8/7/2020 12:05,1,19.0,BIT,Year 1,2,0,1,1,1,0
3,8/7/2020 12:06,0,22.0,Laws,year 3,2,1,1,0,0,0
4,8/7/2020 12:13,1,23.0,Mathemathics,year 4,2,0,0,0,0,0
5,8/7/2020 12:31,1,19.0,Engineering,Year 2,1,0,0,0,1,0
6,8/7/2020 12:32,0,23.0,Pendidikan islam,year 2,1,1,1,0,1,0
7,8/7/2020 12:33,0,18.0,BCS,year 1,1,0,0,1,0,0
8,8/7/2020 12:35,0,19.0,Human Resources,Year 2,3,0,0,0,0,0
9,8/7/2020 12:39,1,18.0,Irkhs,year 1,1,0,0,1,1,0
10,8/7/2020 12:39,0,20.0,Psychology,year 1,1,0,0,0,0,0
11,8/7/2020 12:39,0,24.0,Engineering,Year 3,1,1,1,0,0,0
12,8/7/2020 12:40,0,18.0,BCS,year 1,2,0,1,0,0,0
13,8/7/2020 12:41,1,19.0,Engineering,year 1,2,0,0,0,0,0
14,8/7/2020 12:43,0,18.0,KENMS,Year 2,1,0,0,1,0,0
15,8/7/2020 12:43,1,24.0,BCS,Year 3,1,0,0,0,0,0
16,8/7/2020 12:46,0,24.0,Accounting,year 3,2,0,0,0,0,0
17,8/7/2020 12:52,0,24.0,ENM,year 4,2,1,1,1,1,0
18,8/7/2020 13:05,0,20.0,BIT,Year 2,1,0,0,1,0,0
19,8/7/2020 13:07,0,18.0,Marine science,year 2,1,1,1,1,1,0
20,8/7/2020 13:12,0,19.0,Engineering,year 1,2,0,0,0,1,0
21,8/7/2020 13:13,0,18.0,KOE,Year 2,2,0,0,0,0,0
22,8/7/2020 13:13,0,24.0,BCS,year 1,1,0,0,0,0,0
23,8/7/2020 13:15,0,24.0,Engineering,year 1,2,0,0,0,0,0
24,8/7/2020 13:17,0,23.0,BCS,Year 3,1,0,1,1,1,0
25,8/7/2020 13:29,0,18.0,Banking Studies,year 1,1,0,0,0,0,0
26,8/7/2020 13:35,0,19.0,Engineering,year 1,1,0,0,0,0,0
27,8/7/2020 13:41,1,18.0,Engineering,Year 2,2,1,1,1,0,0
28,8/7/2020 13:58,0,24.0,BIT,Year 3,1,1,1,1,1,1
29,8/7/2020 14:05,0,24.0,BCS,year 4,1,0,0,0,0,0
30,8/7/2020 14:27,0,23.0,Business Administration,Year 2,2,0,0,0,0,0
31,8/7/2020 14:29,1,18.0,BCS,year 2,2,0,0,0,0,0
32,8/7/2020 14:29,1,19.0,BCS,year 1,1,0,0,0,1,0
33,8/7/2020 14:31,1,18.0,BCS,Year 2,1,1,1,1,0,1
34,8/7/2020 14:41,0,19.0,BIT,year 1,2,0,1,1,1,0
35,8/7/2020 14:43,0,18.0,Engineering,year 1,4,0,0,0,0,0
36,8/7/2020 14:43,0,18.0,Law,Year 3,2,0,1,1,0,0
37,8/7/2020 14:45,0,19.0,BIT,year 1,3,0,1,1,1,0
38,8/7/2020 14:47,0,18.0,KIRKHS,year 1,1,0,0,0,0,0
39,8/7/2020 14:56,0,24.0,Engineering,Year 2,3,1,1,0,1,1
40,8/7/2020 14:57,0,24.0,BIT,Year 3,2,0,0,1,0,0
41,8/7/2020 14:57,0,22.0,Engineering,year 4,1,0,0,0,0,0
42,8/7/2020 14:58,0,20.0,Usuluddin,year 2,2,0,1,0,0,0
43,8/7/2020 15:07,1,0.0,BIT,year 1,5,0,0,0,0,0
44,8/7/2020 15:08,1,23.0,TAASL,year 2,1,0,0,0,1,0
45,8/7/2020 15:09,1,18.0,BCS,year 1,1,0,0,1,1,0
46,8/7/2020 15:12,0,19.0,Engineering,year 1,1,0,0,1,0,0
47,8/7/2020 15:14,0,18.0,Engine,year 4,1,0,0,0,0,0
48,8/7/2020 15:14,1,24.0,BCS,year 2,2,0,1,0,0,0
49,8/7/2020 15:18,0,24.0,BCS,year 3,1,0,0,0,1,0
50,8/7/2020 15:27,0,23.0,ALA,year 1,3,1,1,0,1,1
51,8/7/2020 15:37,0,18.0,BCS,year 2,1,0,0,1,0,0
52,8/7/2020 15:47,0,19.0,Biomedical science,year 3,2,0,0,0,0,0
53,8/7/2020 15:48,0,20.0,koe,year 3,2,1,1,1,1,0
54,8/7/2020 15:57,0,19.0,BCS,year 1,1,0,1,0,1,1
55,8/7/2020 15:58,1,21.0,BCS,year 1,2,0,0,0,0,0
56,8/7/2020 16:08,1,23.0,Kirkhs,Year 3,1,0,0,0,0,0
57,8/7/2020 16:21,0,20.0,BENL,Year 3,2,0,1,1,0,0
58,8/7/2020 16:22,0,18.0,BCS,year 1,1,0,0,0,0,0
59,8/7/2020 16:34,0,23.0,Benl,year 1,2,0,0,0,0,0
60,8/7/2020 16:34,0,18.0,IT,Year 3,2,0,0,0,1,0
61,8/7/2020 16:53,0,19.0,BCS,year 1,1,0,0,0,0,0
62,8/7/2020 17:05,0,18.0,CTS,Year 1,1,0,0,0,1,0
63,8/7/2020 17:37,0,24.0,engin,year 1,1,0,0,0,1,0
64,8/7/2020 17:46,0,24.0,Engine,year 1,1,0,0,0,0,0
65,8/7/2020 17:50,0,23.0,Econs,year 1,1,0,1,1,0,0
66,8/7/2020 18:10,0,18.0,KOE,Year 3,2,0,0,1,0,0
67,8/7/2020 18:11,1,19.0,MHSC,Year 3,2,1,1,0,1,0
68,8/7/2020 19:05,0,18.0,Malcom,year 1,1,0,1,0,0,0
69,8/7/2020 19:32,0,24.0,Kop,year 4,2,0,0,1,0,0
70,8/7/2020 20:36,0,24.0,Biomedical science,year 1,2,0,0,0,0,0
71,8/7/2020 21:21,0,18.0,Laws,Year 3,1,0,0,0,1,0
72,8/7/2020 22:35,0,19.0,BIT,Year 3,2,1,1,0,0,0
73,9/7/2020 6:57,1,18.0,Biomedical science,year 1,5,0,0,0,0,0
74,9/7/2020 11:43,1,24.0,BIT,Year 3,1,0,0,1,0,0
75,9/7/2020 11:57,0,24.0,KOE,year 1,1,0,0,1,1,0
76,9/7/2020 13:15,0,23.0,Engineering,year 1,2,0,1,0,0,0
77,9/7/2020 18:24,0,18.0,Human Sciences,Year 2,2,0,0,0,1,0
78,13/07/2020 10:07:32,0,19.0,Biotechnology,Year 3,5,0,0,0,0,0
79,13/07/2020 10:10:30,0,18.0,Engineering,year 4,1,0,0,0,0,0
80,13/07/2020 10:11:26,0,24.0,Communication,Year 2,1,1,1,1,1,0
81,13/07/2020 10:12:18,0,24.0,Diploma Nursing,year 2,1,0,0,0,0,0
82,13/07/2020 10:12:26,0,19.0,Engineering,year 1,2,0,1,1,0,0
83,13/07/2020 10:12:28,0,19.0,Pendidikan Islam,Year 2,2,0,0,0,0,0
84,13/07/2020 10:14:46,1,23.0,Radiography,year 1,2,0,0,0,0,0
85,13/07/2020 10:33:47,0,18.0,psychology,year 1,1,0,1,1,0,1
86,13/07/2020 10:34:08,0,19.0,Fiqh fatwa,Year 3,2,0,0,0,0,0
87,13/07/2020 11:46:13,0,18.0,psychology,year 1,1,0,1,1,1,0
88,13/07/2020 11:49:02,1,24.0,BIT,year 1,2,0,0,1,0,0
89,13/07/2020 11:54:58,1,24.0,Engineering,Year 2,4,0,0,0,1,0
90,13/07/2020 13:57:11,0,23.0,DIPLOMA TESL,Year 3,1,0,0,0,1,0
91,13/07/2020 14:38:12,1,18.0,Koe,Year 2,2,0,0,1,0,0
92,13/07/2020 14:48:05,0,19.0,KOE,year 2,2,1,1,0,0,0
93,13/07/2020 16:15:13,0,18.0,BENL,year 1,2,0,1,0,0,0
94,13/07/2020 17:30:44,0,24.0,Fiqh,Year 3,5,0,0,0,1,0
95,13/07/2020 19:08:32,0,18.0,Islamic Education,year 1,1,0,0,0,0,0
96,13/07/2020 19:56:49,0,21.0,BCS,year 1,1,0,0,1,0,0
97,13/07/2020 21:21:42,1,18.0,Engineering,Year 2,2,0,1,1,0,0
98,13/07/2020 21:22:56,0,19.0,Nursing,Year 3,1,1,1,0,1,0
99,13/07/2020 21:23:57,0,23.0,Pendidikan Islam,year 4,1,0,0,0,0,0
100,18/07/2020 20:16:21,1,20.0,Biomedical science,Year 2,2,0,0,0,0,0

In [25]:
x=mental[["Choose your gender","Marital status","Do you have Depression?","Do you have Anxiety?","Do you have Panic attack?","Did you seek any specialist for a treatment?"]]
y=mental["What is your CGPA?"]

# split your X and Y

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=0)

In [28]:
from sklearn.linear_model import LogisticRegression

# Train and fit the model
# use either logistics or knn modelling for classification
# linear is used for numerical values

In [29]:
model = LogisticRegression().fit(x_train,y_train)

In [30]:
model.predict(x_train)

array([1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2,
       1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1,
       2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1], dtype=int64)

In [31]:
y_predict=model.predict(x_train)

In [32]:
# checking the output in the dataset and predicted values

In [33]:
table=pd.DataFrame(y_train)
# store the x_train in the table variable

In [34]:
# create a new column in table
table["prediction"]=y_predict

In [35]:
table

     What is your CGPA?  prediction
62                    1           1
3                     2           2
71                    1           1
45                    1           1
48                    2           2
6                     1           1
100                   2           2
82                    2           2
76                    2           2
60                    2           1
80                    1           1
91                    2           2
68                    1           2
51                    1           1
27                    2           2
18                    1           1
56                    1           2
63                    1           1
74                    1           2
1                     2           2
61                    1           1
42                    2           2
41                    1           1
4                     2           2
15                    1           2
17                    2           1
40                    2           1
38                    1           1
5                     1           1
92                    2           2
59                    2           1
0                     2           1
34                    2           1
28                    1           1
50                    3           1
11                    1           2
35                    4           1
23                    2           1
52                    2           1
10                    1           1
31                    2           2
66                    2           1
57                    2           2
79                    1           1
85                    1           1
32                    1           1
84                    2           2
14                    1           1
90                    1           1
19                    1           1
29                    1           1
49                    1           1
98                    1           1
99                    1           1
69                    2           1
20                    2           1
95                    1           1
72                    2           2
77                    2           1
25                    1           1
37                    3           1
81                    1           1
46                    1           1
39                    3           1
65                    1           2
58                    1           1
12                    2           2
89                    4           1
88                    2           2
70                    2           1
87                    1           1
36                    2           2
21                    2           1
83                    2           1
9                     1           1
97                    2           2
67                    2           2
64                    1           1
47                    1           1
44                    1           1

# NOW PREDICT FOR THE REMAIN PORTION
# WHICH IS THE X_TEST

In [36]:
x_predict=model.predict(x_test)

In [37]:
table2=pd.DataFrame(y_test)
# store the x_test in the new variable

In [38]:
#create a new column in the table
table2["prediction"]=x_predict

In [39]:
table2

    What is your CGPA?  prediction
26                   1           1
86                   2           1
2                    2           2
55                   2           2
75                   1           1
94                   5           1
16                   2           1
73                   5           2
54                   1           1
96                   1           1
53                   2           1
93                   2           2
78                   5           1
13                   2           2
7                    1           1
30                   2           1
22                   1           1
24                   1           1
33                   1           2
8                    3           1
43                   5           2

In [40]:
# bringing the y_train and y_test together
#and the prediction on x_train and x_test
comparison=pd.concat([table, table2],axis=0)

In [41]:
comparison= comparison.sort_index()

In [42]:
comparison

     What is your CGPA?  prediction
0                     2           1
1                     2           2
2                     2           2
3                     2           2
4                     2           2
5                     1           1
6                     1           1
7                     1           1
8                     3           1
9                     1           1
10                    1           1
11                    1           2
12                    2           2
13                    2           2
14                    1           1
15                    1           2
16                    2           1
17                    2           1
18                    1           1
19                    1           1
20                    2           1
21                    2           1
22                    1           1
23                    2           1
24                    1           1
25                    1           1
26                    1           1
27                    2           2
28                    1           1
29                    1           1
30                    2           1
31                    2           2
32                    1           1
33                    1           2
34                    2           1
35                    4           1
36                    2           2
37                    3           1
38                    1           1
39                    3           1
40                    2           1
41                    1           1
42                    2           2
43                    5           2
44                    1           1
45                    1           1
46                    1           1
47                    1           1
48                    2           2
49                    1           1
50                    3           1
51                    1           1
52                    2           1
53                    2           1
54                    1           1
55                    2           2
56                    1           2
57                    2           2
58                    1           1
59                    2           1
60                    2           1
61                    1           1
62                    1           1
63                    1           1
64                    1           1
65                    1           2
66                    2           1
67                    2           2
68                    1           2
69                    2           1
70                    2           1
71                    1           1
72                    2           2
73                    5           2
74                    1           2
75                    1           1
76                    2           2
77                    2           1
78                    5           1
79                    1           1
80                    1           1
81                    1           1
82                    2           2
83                    2           1
84                    2           2
85                    1           1
86                    2           1
87                    1           1
88                    2           2
89                    4           1
90                    1           1
91                    2           2
92                    2           2
93                    2           2
94                    5           1
95                    1           1
96                    1           1
97                    2           2
98                    1           1
99                    1           1
100                   2           2

In [43]:
#using the insert function to put a column into a dataframe
#and insert takes 3 function
# 1 position
# 2 COLUMN NAME
#3 VALUES TO BE IN THE COLUMN

mental.insert(6,"prediction",comparison["prediction"])

#or using this 

# mental["prediction"]=comparison["prediction"]

In [44]:
mental

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,prediction,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,0,18.0,Engineering,year 1,2,1,0,1,0,1,0
1,8/7/2020 12:04,1,21.0,Islamic education,year 2,2,2,0,0,1,0,0
2,8/7/2020 12:05,1,19.0,BIT,Year 1,2,2,0,1,1,1,0
3,8/7/2020 12:06,0,22.0,Laws,year 3,2,2,1,1,0,0,0
4,8/7/2020 12:13,1,23.0,Mathemathics,year 4,2,2,0,0,0,0,0
5,8/7/2020 12:31,1,19.0,Engineering,Year 2,1,1,0,0,0,1,0
6,8/7/2020 12:32,0,23.0,Pendidikan islam,year 2,1,1,1,1,0,1,0
7,8/7/2020 12:33,0,18.0,BCS,year 1,1,1,0,0,1,0,0
8,8/7/2020 12:35,0,19.0,Human Resources,Year 2,3,1,0,0,0,0,0
9,8/7/2020 12:39,1,18.0,Irkhs,year 1,1,1,0,0,1,1,0
10,8/7/2020 12:39,0,20.0,Psychology,year 1,1,1,0,0,0,0,0
11,8/7/2020 12:39,0,24.0,Engineering,Year 3,1,2,1,1,0,0,0
12,8/7/2020 12:40,0,18.0,BCS,year 1,2,2,0,1,0,0,0
13,8/7/2020 12:41,1,19.0,Engineering,year 1,2,2,0,0,0,0,0
14,8/7/2020 12:43,0,18.0,KENMS,Year 2,1,1,0,0,1,0,0
15,8/7/2020 12:43,1,24.0,BCS,Year 3,1,2,0,0,0,0,0
16,8/7/2020 12:46,0,24.0,Accounting,year 3,2,1,0,0,0,0,0
17,8/7/2020 12:52,0,24.0,ENM,year 4,2,1,1,1,1,1,0
18,8/7/2020 13:05,0,20.0,BIT,Year 2,1,1,0,0,1,0,0
19,8/7/2020 13:07,0,18.0,Marine science,year 2,1,1,1,1,1,1,0
20,8/7/2020 13:12,0,19.0,Engineering,year 1,2,1,0,0,0,1,0
21,8/7/2020 13:13,0,18.0,KOE,Year 2,2,1,0,0,0,0,0
22,8/7/2020 13:13,0,24.0,BCS,year 1,1,1,0,0,0,0,0
23,8/7/2020 13:15,0,24.0,Engineering,year 1,2,1,0,0,0,0,0
24,8/7/2020 13:17,0,23.0,BCS,Year 3,1,1,0,1,1,1,0
25,8/7/2020 13:29,0,18.0,Banking Studies,year 1,1,1,0,0,0,0,0
26,8/7/2020 13:35,0,19.0,Engineering,year 1,1,1,0,0,0,0,0
27,8/7/2020 13:41,1,18.0,Engineering,Year 2,2,2,1,1,1,0,0
28,8/7/2020 13:58,0,24.0,BIT,Year 3,1,1,1,1,1,1,1
29,8/7/2020 14:05,0,24.0,BCS,year 4,1,1,0,0,0,0,0
30,8/7/2020 14:27,0,23.0,Business Administration,Year 2,2,1,0,0,0,0,0
31,8/7/2020 14:29,1,18.0,BCS,year 2,2,2,0,0,0,0,0
32,8/7/2020 14:29,1,19.0,BCS,year 1,1,1,0,0,0,1,0
33,8/7/2020 14:31,1,18.0,BCS,Year 2,1,2,1,1,1,0,1
34,8/7/2020 14:41,0,19.0,BIT,year 1,2,1,0,1,1,1,0
35,8/7/2020 14:43,0,18.0,Engineering,year 1,4,1,0,0,0,0,0
36,8/7/2020 14:43,0,18.0,Law,Year 3,2,2,0,1,1,0,0
37,8/7/2020 14:45,0,19.0,BIT,year 1,3,1,0,1,1,1,0
38,8/7/2020 14:47,0,18.0,KIRKHS,year 1,1,1,0,0,0,0,0
39,8/7/2020 14:56,0,24.0,Engineering,Year 2,3,1,1,1,0,1,1
40,8/7/2020 14:57,0,24.0,BIT,Year 3,2,1,0,0,1,0,0
41,8/7/2020 14:57,0,22.0,Engineering,year 4,1,1,0,0,0,0,0
42,8/7/2020 14:58,0,20.0,Usuluddin,year 2,2,2,0,1,0,0,0
43,8/7/2020 15:07,1,0.0,BIT,year 1,5,2,0,0,0,0,0
44,8/7/2020 15:08,1,23.0,TAASL,year 2,1,1,0,0,0,1,0
45,8/7/2020 15:09,1,18.0,BCS,year 1,1,1,0,0,1,1,0
46,8/7/2020 15:12,0,19.0,Engineering,year 1,1,1,0,0,1,0,0
47,8/7/2020 15:14,0,18.0,Engine,year 4,1,1,0,0,0,0,0
48,8/7/2020 15:14,1,24.0,BCS,year 2,2,2,0,1,0,0,0
49,8/7/2020 15:18,0,24.0,BCS,year 3,1,1,0,0,0,1,0
50,8/7/2020 15:27,0,23.0,ALA,year 1,3,1,1,1,0,1,1
51,8/7/2020 15:37,0,18.0,BCS,year 2,1,1,0,0,1,0,0
52,8/7/2020 15:47,0,19.0,Biomedical science,year 3,2,1,0,0,0,0,0
53,8/7/2020 15:48,0,20.0,koe,year 3,2,1,1,1,1,1,0
54,8/7/2020 15:57,0,19.0,BCS,year 1,1,1,0,1,0,1,1
55,8/7/2020 15:58,1,21.0,BCS,year 1,2,2,0,0,0,0,0
56,8/7/2020 16:08,1,23.0,Kirkhs,Year 3,1,2,0,0,0,0,0
57,8/7/2020 16:21,0,20.0,BENL,Year 3,2,2,0,1,1,0,0
58,8/7/2020 16:22,0,18.0,BCS,year 1,1,1,0,0,0,0,0
59,8/7/2020 16:34,0,23.0,Benl,year 1,2,1,0,0,0,0,0
60,8/7/2020 16:34,0,18.0,IT,Year 3,2,1,0,0,0,1,0
61,8/7/2020 16:53,0,19.0,BCS,year 1,1,1,0,0,0,0,0
62,8/7/2020 17:05,0,18.0,CTS,Year 1,1,1,0,0,0,1,0
63,8/7/2020 17:37,0,24.0,engin,year 1,1,1,0,0,0,1,0
64,8/7/2020 17:46,0,24.0,Engine,year 1,1,1,0,0,0,0,0
65,8/7/2020 17:50,0,23.0,Econs,year 1,1,2,0,1,1,0,0
66,8/7/2020 18:10,0,18.0,KOE,Year 3,2,1,0,0,1,0,0
67,8/7/2020 18:11,1,19.0,MHSC,Year 3,2,2,1,1,0,1,0
68,8/7/2020 19:05,0,18.0,Malcom,year 1,1,2,0,1,0,0,0
69,8/7/2020 19:32,0,24.0,Kop,year 4,2,1,0,0,1,0,0
70,8/7/2020 20:36,0,24.0,Biomedical science,year 1,2,1,0,0,0,0,0
71,8/7/2020 21:21,0,18.0,Laws,Year 3,1,1,0,0,0,1,0
72,8/7/2020 22:35,0,19.0,BIT,Year 3,2,2,1,1,0,0,0
73,9/7/2020 6:57,1,18.0,Biomedical science,year 1,5,2,0,0,0,0,0
74,9/7/2020 11:43,1,24.0,BIT,Year 3,1,2,0,0,1,0,0
75,9/7/2020 11:57,0,24.0,KOE,year 1,1,1,0,0,1,1,0
76,9/7/2020 13:15,0,23.0,Engineering,year 1,2,2,0,1,0,0,0
77,9/7/2020 18:24,0,18.0,Human Sciences,Year 2,2,1,0,0,0,1,0
78,13/07/2020 10:07:32,0,19.0,Biotechnology,Year 3,5,1,0,0,0,0,0
79,13/07/2020 10:10:30,0,18.0,Engineering,year 4,1,1,0,0,0,0,0
80,13/07/2020 10:11:26,0,24.0,Communication,Year 2,1,1,1,1,1,1,0
81,13/07/2020 10:12:18,0,24.0,Diploma Nursing,year 2,1,1,0,0,0,0,0
82,13/07/2020 10:12:26,0,19.0,Engineering,year 1,2,2,0,1,1,0,0
83,13/07/2020 10:12:28,0,19.0,Pendidikan Islam,Year 2,2,1,0,0,0,0,0
84,13/07/2020 10:14:46,1,23.0,Radiography,year 1,2,2,0,0,0,0,0
85,13/07/2020 10:33:47,0,18.0,psychology,year 1,1,1,0,1,1,0,1
86,13/07/2020 10:34:08,0,19.0,Fiqh fatwa,Year 3,2,1,0,0,0,0,0
87,13/07/2020 11:46:13,0,18.0,psychology,year 1,1,1,0,1,1,1,0
88,13/07/2020 11:49:02,1,24.0,BIT,year 1,2,2,0,0,1,0,0
89,13/07/2020 11:54:58,1,24.0,Engineering,Year 2,4,1,0,0,0,1,0
90,13/07/2020 13:57:11,0,23.0,DIPLOMA TESL,Year 3,1,1,0,0,0,1,0
91,13/07/2020 14:38:12,1,18.0,Koe,Year 2,2,2,0,0,1,0,0
92,13/07/2020 14:48:05,0,19.0,KOE,year 2,2,2,1,1,0,0,0
93,13/07/2020 16:15:13,0,18.0,BENL,year 1,2,2,0,1,0,0,0
94,13/07/2020 17:30:44,0,24.0,Fiqh,Year 3,5,1,0,0,0,1,0
95,13/07/2020 19:08:32,0,18.0,Islamic Education,year 1,1,1,0,0,0,0,0
96,13/07/2020 19:56:49,0,21.0,BCS,year 1,1,1,0,0,1,0,0
97,13/07/2020 21:21:42,1,18.0,Engineering,Year 2,2,2,0,1,1,0,0
98,13/07/2020 21:22:56,0,19.0,Nursing,Year 3,1,1,1,1,0,1,0
99,13/07/2020 21:23:57,0,23.0,Pendidikan Islam,year 4,1,1,0,0,0,0,0
100,18/07/2020 20:16:21,1,20.0,Biomedical science,Year 2,2,2,0,0,0,0,0

In [45]:
# replacing all the values in the prediction column

#1 - first class
#2 - second class
#3 - third class
#4 - pass
#5 - fail

In [48]:
mental["What is your CGPA?"]=mental["What is your CGPA?"].astype(str)

In [51]:
mental["What is your CGPA?"].str.replace("1","First Class").str.replace("2" ,"Second Class").str.replace("3","Third Class")\
.str.replace("4","Pass").str.replace("5","Fail")

0      Second Class
1      Second Class
2      Second Class
3      Second Class
4      Second Class
5       First Class
6       First Class
7       First Class
8       Third Class
9       First Class
10      First Class
11      First Class
12     Second Class
13     Second Class
14      First Class
15      First Class
16     Second Class
17     Second Class
18      First Class
19      First Class
20     Second Class
21     Second Class
22      First Class
23     Second Class
24      First Class
25      First Class
26      First Class
27     Second Class
28      First Class
29      First Class
30     Second Class
31     Second Class
32      First Class
33      First Class
34     Second Class
35             Pass
36     Second Class
37      Third Class
38      First Class
39      Third Class
40     Second Class
41      First Class
42     Second Class
43             Fail
44      First Class
45      First Class
46      First Class
47      First Class
48     Second Class
49      First Class
50      Third Class
51      First Class
52     Second Class
53     Second Class
54      First Class
55     Second Class
56      First Class
57     Second Class
58      First Class
59     Second Class
60     Second Class
61      First Class
62      First Class
63      First Class
64      First Class
65      First Class
66     Second Class
67     Second Class
68      First Class
69     Second Class
70     Second Class
71      First Class
72     Second Class
73             Fail
74      First Class
75      First Class
76     Second Class
77     Second Class
78             Fail
79      First Class
80      First Class
81      First Class
82     Second Class
83     Second Class
84     Second Class
85      First Class
86     Second Class
87      First Class
88     Second Class
89             Pass
90      First Class
91     Second Class
92     Second Class
93     Second Class
94             Fail
95      First Class
96      First Class
97     Second Class
98      First Class
99      First Class
100    Second Class
Name: What is your CGPA?, dtype: object

In [52]:
#assign to a variable
mental["What is your CGPA?"]=mental["What is your CGPA?"].str.replace("1","First Class").str.replace("2" ,"Second Class").str.replace("3","Third Class")\
.str.replace("4","Pass").str.replace("5","Fail")

In [53]:
mental

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,prediction,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,0,18.0,Engineering,year 1,Second Class,1,0,1,0,1,0
1,8/7/2020 12:04,1,21.0,Islamic education,year 2,Second Class,2,0,0,1,0,0
2,8/7/2020 12:05,1,19.0,BIT,Year 1,Second Class,2,0,1,1,1,0
3,8/7/2020 12:06,0,22.0,Laws,year 3,Second Class,2,1,1,0,0,0
4,8/7/2020 12:13,1,23.0,Mathemathics,year 4,Second Class,2,0,0,0,0,0
5,8/7/2020 12:31,1,19.0,Engineering,Year 2,First Class,1,0,0,0,1,0
6,8/7/2020 12:32,0,23.0,Pendidikan islam,year 2,First Class,1,1,1,0,1,0
7,8/7/2020 12:33,0,18.0,BCS,year 1,First Class,1,0,0,1,0,0
8,8/7/2020 12:35,0,19.0,Human Resources,Year 2,Third Class,1,0,0,0,0,0
9,8/7/2020 12:39,1,18.0,Irkhs,year 1,First Class,1,0,0,1,1,0
10,8/7/2020 12:39,0,20.0,Psychology,year 1,First Class,1,0,0,0,0,0
11,8/7/2020 12:39,0,24.0,Engineering,Year 3,First Class,2,1,1,0,0,0
12,8/7/2020 12:40,0,18.0,BCS,year 1,Second Class,2,0,1,0,0,0
13,8/7/2020 12:41,1,19.0,Engineering,year 1,Second Class,2,0,0,0,0,0
14,8/7/2020 12:43,0,18.0,KENMS,Year 2,First Class,1,0,0,1,0,0
15,8/7/2020 12:43,1,24.0,BCS,Year 3,First Class,2,0,0,0,0,0
16,8/7/2020 12:46,0,24.0,Accounting,year 3,Second Class,1,0,0,0,0,0
17,8/7/2020 12:52,0,24.0,ENM,year 4,Second Class,1,1,1,1,1,0
18,8/7/2020 13:05,0,20.0,BIT,Year 2,First Class,1,0,0,1,0,0
19,8/7/2020 13:07,0,18.0,Marine science,year 2,First Class,1,1,1,1,1,0
20,8/7/2020 13:12,0,19.0,Engineering,year 1,Second Class,1,0,0,0,1,0
21,8/7/2020 13:13,0,18.0,KOE,Year 2,Second Class,1,0,0,0,0,0
22,8/7/2020 13:13,0,24.0,BCS,year 1,First Class,1,0,0,0,0,0
23,8/7/2020 13:15,0,24.0,Engineering,year 1,Second Class,1,0,0,0,0,0
24,8/7/2020 13:17,0,23.0,BCS,Year 3,First Class,1,0,1,1,1,0
25,8/7/2020 13:29,0,18.0,Banking Studies,year 1,First Class,1,0,0,0,0,0
26,8/7/2020 13:35,0,19.0,Engineering,year 1,First Class,1,0,0,0,0,0
27,8/7/2020 13:41,1,18.0,Engineering,Year 2,Second Class,2,1,1,1,0,0
28,8/7/2020 13:58,0,24.0,BIT,Year 3,First Class,1,1,1,1,1,1
29,8/7/2020 14:05,0,24.0,BCS,year 4,First Class,1,0,0,0,0,0
30,8/7/2020 14:27,0,23.0,Business Administration,Year 2,Second Class,1,0,0,0,0,0
31,8/7/2020 14:29,1,18.0,BCS,year 2,Second Class,2,0,0,0,0,0
32,8/7/2020 14:29,1,19.0,BCS,year 1,First Class,1,0,0,0,1,0
33,8/7/2020 14:31,1,18.0,BCS,Year 2,First Class,2,1,1,1,0,1
34,8/7/2020 14:41,0,19.0,BIT,year 1,Second Class,1,0,1,1,1,0
35,8/7/2020 14:43,0,18.0,Engineering,year 1,Pass,1,0,0,0,0,0
36,8/7/2020 14:43,0,18.0,Law,Year 3,Second Class,2,0,1,1,0,0
37,8/7/2020 14:45,0,19.0,BIT,year 1,Third Class,1,0,1,1,1,0
38,8/7/2020 14:47,0,18.0,KIRKHS,year 1,First Class,1,0,0,0,0,0
39,8/7/2020 14:56,0,24.0,Engineering,Year 2,Third Class,1,1,1,0,1,1
40,8/7/2020 14:57,0,24.0,BIT,Year 3,Second Class,1,0,0,1,0,0
41,8/7/2020 14:57,0,22.0,Engineering,year 4,First Class,1,0,0,0,0,0
42,8/7/2020 14:58,0,20.0,Usuluddin,year 2,Second Class,2,0,1,0,0,0
43,8/7/2020 15:07,1,0.0,BIT,year 1,Fail,2,0,0,0,0,0
44,8/7/2020 15:08,1,23.0,TAASL,year 2,First Class,1,0,0,0,1,0
45,8/7/2020 15:09,1,18.0,BCS,year 1,First Class,1,0,0,1,1,0
46,8/7/2020 15:12,0,19.0,Engineering,year 1,First Class,1,0,0,1,0,0
47,8/7/2020 15:14,0,18.0,Engine,year 4,First Class,1,0,0,0,0,0
48,8/7/2020 15:14,1,24.0,BCS,year 2,Second Class,2,0,1,0,0,0
49,8/7/2020 15:18,0,24.0,BCS,year 3,First Class,1,0,0,0,1,0
50,8/7/2020 15:27,0,23.0,ALA,year 1,Third Class,1,1,1,0,1,1
51,8/7/2020 15:37,0,18.0,BCS,year 2,First Class,1,0,0,1,0,0
52,8/7/2020 15:47,0,19.0,Biomedical science,year 3,Second Class,1,0,0,0,0,0
53,8/7/2020 15:48,0,20.0,koe,year 3,Second Class,1,1,1,1,1,0
54,8/7/2020 15:57,0,19.0,BCS,year 1,First Class,1,0,1,0,1,1
55,8/7/2020 15:58,1,21.0,BCS,year 1,Second Class,2,0,0,0,0,0
56,8/7/2020 16:08,1,23.0,Kirkhs,Year 3,First Class,2,0,0,0,0,0
57,8/7/2020 16:21,0,20.0,BENL,Year 3,Second Class,2,0,1,1,0,0
58,8/7/2020 16:22,0,18.0,BCS,year 1,First Class,1,0,0,0,0,0
59,8/7/2020 16:34,0,23.0,Benl,year 1,Second Class,1,0,0,0,0,0
60,8/7/2020 16:34,0,18.0,IT,Year 3,Second Class,1,0,0,0,1,0
61,8/7/2020 16:53,0,19.0,BCS,year 1,First Class,1,0,0,0,0,0
62,8/7/2020 17:05,0,18.0,CTS,Year 1,First Class,1,0,0,0,1,0
63,8/7/2020 17:37,0,24.0,engin,year 1,First Class,1,0,0,0,1,0
64,8/7/2020 17:46,0,24.0,Engine,year 1,First Class,1,0,0,0,0,0
65,8/7/2020 17:50,0,23.0,Econs,year 1,First Class,2,0,1,1,0,0
66,8/7/2020 18:10,0,18.0,KOE,Year 3,Second Class,1,0,0,1,0,0
67,8/7/2020 18:11,1,19.0,MHSC,Year 3,Second Class,2,1,1,0,1,0
68,8/7/2020 19:05,0,18.0,Malcom,year 1,First Class,2,0,1,0,0,0
69,8/7/2020 19:32,0,24.0,Kop,year 4,Second Class,1,0,0,1,0,0
70,8/7/2020 20:36,0,24.0,Biomedical science,year 1,Second Class,1,0,0,0,0,0
71,8/7/2020 21:21,0,18.0,Laws,Year 3,First Class,1,0,0,0,1,0
72,8/7/2020 22:35,0,19.0,BIT,Year 3,Second Class,2,1,1,0,0,0
73,9/7/2020 6:57,1,18.0,Biomedical science,year 1,Fail,2,0,0,0,0,0
74,9/7/2020 11:43,1,24.0,BIT,Year 3,First Class,2,0,0,1,0,0
75,9/7/2020 11:57,0,24.0,KOE,year 1,First Class,1,0,0,1,1,0
76,9/7/2020 13:15,0,23.0,Engineering,year 1,Second Class,2,0,1,0,0,0
77,9/7/2020 18:24,0,18.0,Human Sciences,Year 2,Second Class,1,0,0,0,1,0
78,13/07/2020 10:07:32,0,19.0,Biotechnology,Year 3,Fail,1,0,0,0,0,0
79,13/07/2020 10:10:30,0,18.0,Engineering,year 4,First Class,1,0,0,0,0,0
80,13/07/2020 10:11:26,0,24.0,Communication,Year 2,First Class,1,1,1,1,1,0
81,13/07/2020 10:12:18,0,24.0,Diploma Nursing,year 2,First Class,1,0,0,0,0,0
82,13/07/2020 10:12:26,0,19.0,Engineering,year 1,Second Class,2,0,1,1,0,0
83,13/07/2020 10:12:28,0,19.0,Pendidikan Islam,Year 2,Second Class,1,0,0,0,0,0
84,13/07/2020 10:14:46,1,23.0,Radiography,year 1,Second Class,2,0,0,0,0,0
85,13/07/2020 10:33:47,0,18.0,psychology,year 1,First Class,1,0,1,1,0,1
86,13/07/2020 10:34:08,0,19.0,Fiqh fatwa,Year 3,Second Class,1,0,0,0,0,0
87,13/07/2020 11:46:13,0,18.0,psychology,year 1,First Class,1,0,1,1,1,0
88,13/07/2020 11:49:02,1,24.0,BIT,year 1,Second Class,2,0,0,1,0,0
89,13/07/2020 11:54:58,1,24.0,Engineering,Year 2,Pass,1,0,0,0,1,0
90,13/07/2020 13:57:11,0,23.0,DIPLOMA TESL,Year 3,First Class,1,0,0,0,1,0
91,13/07/2020 14:38:12,1,18.0,Koe,Year 2,Second Class,2,0,0,1,0,0
92,13/07/2020 14:48:05,0,19.0,KOE,year 2,Second Class,2,1,1,0,0,0
93,13/07/2020 16:15:13,0,18.0,BENL,year 1,Second Class,2,0,1,0,0,0
94,13/07/2020 17:30:44,0,24.0,Fiqh,Year 3,Fail,1,0,0,0,1,0
95,13/07/2020 19:08:32,0,18.0,Islamic Education,year 1,First Class,1,0,0,0,0,0
96,13/07/2020 19:56:49,0,21.0,BCS,year 1,First Class,1,0,0,1,0,0
97,13/07/2020 21:21:42,1,18.0,Engineering,Year 2,Second Class,2,0,1,1,0,0
98,13/07/2020 21:22:56,0,19.0,Nursing,Year 3,First Class,1,1,1,0,1,0
99,13/07/2020 21:23:57,0,23.0,Pendidikan Islam,year 4,First Class,1,0,0,0,0,0
100,18/07/2020 20:16:21,1,20.0,Biomedical science,Year 2,Second Class,2,0,0,0,0,0