In [1]:
import pandas as pd

In [2]:
mental=pd.read_csv("Student Mental health.csv")

In [3]:
mental

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...
96,13/07/2020 19:56:49,Female,21.0,BCS,year 1,3.50 - 4.00,No,No,Yes,No,No
97,13/07/2020 21:21:42,Male,18.0,Engineering,Year 2,3.00 - 3.49,No,Yes,Yes,No,No
98,13/07/2020 21:22:56,Female,19.0,Nursing,Year 3,3.50 - 4.00,Yes,Yes,No,Yes,No
99,13/07/2020 21:23:57,Female,23.0,Pendidikan Islam,year 4,3.50 - 4.00,No,No,No,No,No
100,18/07/2020 20:16:21,Male,20.0,Biomedical science,Year 2,3.00 - 3.49,No,No,No,No,No

In [4]:
mental.isnull().sum()
#one empty so fill it

Timestamp                                       0
Choose your gender                              0
Age                                             1
What is your course?                            0
Your current year of Study                      0
What is your CGPA?                              0
Marital status                                  0
Do you have Depression?                         0
Do you have Anxiety?                            0
Do you have Panic attack?                       0
Did you seek any specialist for a treatment?    0
dtype: int64

In [5]:
mental=mental.fillna(0)
#fill the empty cell and assign back to grade

In [6]:
mental.dtypes

Timestamp                                        object
Choose your gender                               object
Age                                             float64
What is your course?                             object
Your current year of Study                       object
What is your CGPA?                               object
Marital status                                   object
Do you have Depression?                          object
Do you have Anxiety?                             object
Do you have Panic attack?                        object
Did you seek any specialist for a treatment?     object
dtype: object

In [7]:
#assign each gender 
# male -1
# female - 0
mental["Choose your gender"].map({"Male":1,"Female":0})
#assign back to the dataframe
mental["Choose Your gender"]=mental["Choose your gender"].map({"Male":1,"Female":0})

In [8]:
mental["What is your CGPA?"].unique()

array(['3.00 - 3.49', '3.50 - 4.00', '3.50 - 4.00 ', '2.50 - 2.99',
       '2.00 - 2.49', '0 - 1.99'], dtype=object)

In [9]:
#3.00 - 3.49 - 1
#3.50 - 4.00 - 2
#3.50 - 4.00 - 3
#2.50 - 2.99 -4
#2.00 - 2.49 - 5
# 0 - 1.99 - 6
#the numbers in are seen as objects
mental["What is your CGPA?"].map({"3.00 - 3.49":1,"3.50 - 4.00":2,"3.50 - 4.0":3,"2.50 - 2.99":4,"2.00 - 2.49":5,"0 - 1.99":6 })

mental["What is your CGPA?"]=mental["What is your CGPA?"].map({"3.00 - 3.49":1,"3.50 - 4.00":2,"3.50 - 4.0":3,"2.50 - 2.99":4,"2.00 - 2.49":5,"0 - 1.99":6 })

In [10]:
mental["Marital status"].astype(str)
mental["Marital status"].map({"NO":0,"YES":1})
mental["Marital status"]=mental["Marital status"].map({"No":0,"Yes":1})

In [11]:
mental["Do you have Depression?"].astype(str)
mental["Do you have Depression?"].map({"No":0,"Yes":1})
mental["Do you have Depression?"]=mental["Do you have Depression?"].map({"No":0,"Yes":1})

In [12]:
mental["Do you have Anxiety?"].astype(str)
mental["Do you have Anxiety?"].map({"No":0,"Yes":1})
mental["Do you have Anxiety?"]=mental["Do you have Anxiety?"].map({"No":0,"Yes":1})

In [13]:
mental["Do you have Panic attack?"].astype(str)
mental["Do you have Panic attack?"].map({"No":0,"Yes":1})
mental["Do you have Panic attack?"]=mental["Do you have Panic attack?"].map({"No":0,"Yes":1})

In [14]:
mental["Did you seek any specialist for a treatment?"].astype(str)
mental["Did you seek any specialist for a treatment?"].map({"No":0,"Yes":1})
mental["Did you seek any specialist for a treatment?"]=mental["Did you seek any specialist for a treatment?"].map({"No":0,"Yes":1})

In [15]:
pd.set_option("display.max_rows",None)
mental

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?,Choose Your gender
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,1.0,0,1,0,1,0,0
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,1.0,0,0,1,0,0,1
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,1.0,0,1,1,1,0,1
3,8/7/2020 12:06,Female,22.0,Laws,year 3,1.0,1,1,0,0,0,0
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,1.0,0,0,0,0,0,1
5,8/7/2020 12:31,Male,19.0,Engineering,Year 2,2.0,0,0,0,1,0,1
6,8/7/2020 12:32,Female,23.0,Pendidikan islam,year 2,NaN,1,1,0,1,0,0
7,8/7/2020 12:33,Female,18.0,BCS,year 1,2.0,0,0,1,0,0,0
8,8/7/2020 12:35,Female,19.0,Human Resources,Year 2,4.0,0,0,0,0,0,0
9,8/7/2020 12:39,Male,18.0,Irkhs,year 1,2.0,0,0,1,1,0,1
10,8/7/2020 12:39,Female,20.0,Psychology,year 1,2.0,0,0,0,0,0,0
11,8/7/2020 12:39,Female,24.0,Engineering,Year 3,2.0,1,1,0,0,0,0
12,8/7/2020 12:40,Female,18.0,BCS,year 1,1.0,0,1,0,0,0,0
13,8/7/2020 12:41,Male,19.0,Engineering,year 1,1.0,0,0,0,0,0,1
14,8/7/2020 12:43,Female,18.0,KENMS,Year 2,2.0,0,0,1,0,0,0
15,8/7/2020 12:43,Male,24.0,BCS,Year 3,2.0,0,0,0,0,0,1
16,8/7/2020 12:46,Female,24.0,Accounting,year 3,1.0,0,0,0,0,0,0
17,8/7/2020 12:52,Female,24.0,ENM,year 4,1.0,1,1,1,1,0,0
18,8/7/2020 13:05,Female,20.0,BIT,Year 2,2.0,0,0,1,0,0,0
19,8/7/2020 13:07,Female,18.0,Marine science,year 2,2.0,1,1,1,1,0,0
20,8/7/2020 13:12,Female,19.0,Engineering,year 1,1.0,0,0,0,1,0,0
21,8/7/2020 13:13,Female,18.0,KOE,Year 2,1.0,0,0,0,0,0,0
22,8/7/2020 13:13,Female,24.0,BCS,year 1,2.0,0,0,0,0,0,0
23,8/7/2020 13:15,Female,24.0,Engineering,year 1,1.0,0,0,0,0,0,0
24,8/7/2020 13:17,Female,23.0,BCS,Year 3,2.0,0,1,1,1,0,0
25,8/7/2020 13:29,Female,18.0,Banking Studies,year 1,2.0,0,0,0,0,0,0
26,8/7/2020 13:35,Female,19.0,Engineering,year 1,2.0,0,0,0,0,0,0
27,8/7/2020 13:41,Male,18.0,Engineering,Year 2,1.0,1,1,1,0,0,1
28,8/7/2020 13:58,Female,24.0,BIT,Year 3,2.0,1,1,1,1,1,0
29,8/7/2020 14:05,Female,24.0,BCS,year 4,2.0,0,0,0,0,0,0
30,8/7/2020 14:27,Female,23.0,Business Administration,Year 2,1.0,0,0,0,0,0,0
31,8/7/2020 14:29,Male,18.0,BCS,year 2,1.0,0,0,0,0,0,1
32,8/7/2020 14:29,Male,19.0,BCS,year 1,2.0,0,0,0,1,0,1
33,8/7/2020 14:31,Male,18.0,BCS,Year 2,2.0,1,1,1,0,1,1
34,8/7/2020 14:41,Female,19.0,BIT,year 1,1.0,0,1,1,1,0,0
35,8/7/2020 14:43,Female,18.0,Engineering,year 1,5.0,0,0,0,0,0,0
36,8/7/2020 14:43,Female,18.0,Law,Year 3,1.0,0,1,1,0,0,0
37,8/7/2020 14:45,Female,19.0,BIT,year 1,4.0,0,1,1,1,0,0
38,8/7/2020 14:47,Female,18.0,KIRKHS,year 1,2.0,0,0,0,0,0,0
39,8/7/2020 14:56,Female,24.0,Engineering,Year 2,4.0,1,1,0,1,1,0
40,8/7/2020 14:57,Female,24.0,BIT,Year 3,1.0,0,0,1,0,0,0
41,8/7/2020 14:57,Female,22.0,Engineering,year 4,2.0,0,0,0,0,0,0
42,8/7/2020 14:58,Female,20.0,Usuluddin,year 2,1.0,0,1,0,0,0,0
43,8/7/2020 15:07,Male,0.0,BIT,year 1,6.0,0,0,0,0,0,1
44,8/7/2020 15:08,Male,23.0,TAASL,year 2,2.0,0,0,0,1,0,1
45,8/7/2020 15:09,Male,18.0,BCS,year 1,2.0,0,0,1,1,0,1
46,8/7/2020 15:12,Female,19.0,Engineering,year 1,2.0,0,0,1,0,0,0
47,8/7/2020 15:14,Female,18.0,Engine,year 4,2.0,0,0,0,0,0,0
48,8/7/2020 15:14,Male,24.0,BCS,year 2,1.0,0,1,0,0,0,1
49,8/7/2020 15:18,Female,24.0,BCS,year 3,2.0,0,0,0,1,0,0
50,8/7/2020 15:27,Female,23.0,ALA,year 1,4.0,1,1,0,1,1,0
51,8/7/2020 15:37,Female,18.0,BCS,year 2,2.0,0,0,1,0,0,0
52,8/7/2020 15:47,Female,19.0,Biomedical science,year 3,1.0,0,0,0,0,0,0
53,8/7/2020 15:48,Female,20.0,koe,year 3,1.0,1,1,1,1,0,0
54,8/7/2020 15:57,Female,19.0,BCS,year 1,2.0,0,1,0,1,1,0
55,8/7/2020 15:58,Male,21.0,BCS,year 1,1.0,0,0,0,0,0,1
56,8/7/2020 16:08,Male,23.0,Kirkhs,Year 3,2.0,0,0,0,0,0,1
57,8/7/2020 16:21,Female,20.0,BENL,Year 3,1.0,0,1,1,0,0,0
58,8/7/2020 16:22,Female,18.0,BCS,year 1,2.0,0,0,0,0,0,0
59,8/7/2020 16:34,Female,23.0,Benl,year 1,1.0,0,0,0,0,0,0
60,8/7/2020 16:34,Female,18.0,IT,Year 3,1.0,0,0,0,1,0,0
61,8/7/2020 16:53,Female,19.0,BCS,year 1,2.0,0,0,0,0,0,0
62,8/7/2020 17:05,Female,18.0,CTS,Year 1,2.0,0,0,0,1,0,0
63,8/7/2020 17:37,Female,24.0,engin,year 1,2.0,0,0,0,1,0,0
64,8/7/2020 17:46,Female,24.0,Engine,year 1,2.0,0,0,0,0,0,0
65,8/7/2020 17:50,Female,23.0,Econs,year 1,2.0,0,1,1,0,0,0
66,8/7/2020 18:10,Female,18.0,KOE,Year 3,1.0,0,0,1,0,0,0
67,8/7/2020 18:11,Male,19.0,MHSC,Year 3,1.0,1,1,0,1,0,1
68,8/7/2020 19:05,Female,18.0,Malcom,year 1,2.0,0,1,0,0,0,0
69,8/7/2020 19:32,Female,24.0,Kop,year 4,1.0,0,0,1,0,0,0
70,8/7/2020 20:36,Female,24.0,Biomedical science,year 1,1.0,0,0,0,0,0,0
71,8/7/2020 21:21,Female,18.0,Laws,Year 3,2.0,0,0,0,1,0,0
72,8/7/2020 22:35,Female,19.0,BIT,Year 3,1.0,1,1,0,0,0,0
73,9/7/2020 6:57,Male,18.0,Biomedical science,year 1,6.0,0,0,0,0,0,1
74,9/7/2020 11:43,Male,24.0,BIT,Year 3,2.0,0,0,1,0,0,1
75,9/7/2020 11:57,Female,24.0,KOE,year 1,2.0,0,0,1,1,0,0
76,9/7/2020 13:15,Female,23.0,Engineering,year 1,1.0,0,1,0,0,0,0
77,9/7/2020 18:24,Female,18.0,Human Sciences,Year 2,1.0,0,0,0,1,0,0
78,13/07/2020 10:07:32,Female,19.0,Biotechnology,Year 3,6.0,0,0,0,0,0,0
79,13/07/2020 10:10:30,Female,18.0,Engineering,year 4,2.0,0,0,0,0,0,0
80,13/07/2020 10:11:26,Female,24.0,Communication,Year 2,2.0,1,1,1,1,0,0
81,13/07/2020 10:12:18,Female,24.0,Diploma Nursing,year 2,2.0,0,0,0,0,0,0
82,13/07/2020 10:12:26,Female,19.0,Engineering,year 1,1.0,0,1,1,0,0,0
83,13/07/2020 10:12:28,Female,19.0,Pendidikan Islam,Year 2,1.0,0,0,0,0,0,0
84,13/07/2020 10:14:46,Male,23.0,Radiography,year 1,1.0,0,0,0,0,0,1
85,13/07/2020 10:33:47,Female,18.0,psychology,year 1,2.0,0,1,1,0,1,0
86,13/07/2020 10:34:08,Female,19.0,Fiqh fatwa,Year 3,1.0,0,0,0,0,0,0
87,13/07/2020 11:46:13,Female,18.0,psychology,year 1,2.0,0,1,1,1,0,0
88,13/07/2020 11:49:02,Male,24.0,BIT,year 1,1.0,0,0,1,0,0,1
89,13/07/2020 11:54:58,Male,24.0,Engineering,Year 2,5.0,0,0,0,1,0,1
90,13/07/2020 13:57:11,Female,23.0,DIPLOMA TESL,Year 3,2.0,0,0,0,1,0,0
91,13/07/2020 14:38:12,Male,18.0,Koe,Year 2,1.0,0,0,1,0,0,1
92,13/07/2020 14:48:05,Female,19.0,KOE,year 2,1.0,1,1,0,0,0,0
93,13/07/2020 16:15:13,Female,18.0,BENL,year 1,1.0,0,1,0,0,0,0
94,13/07/2020 17:30:44,Female,24.0,Fiqh,Year 3,6.0,0,0,0,1,0,0
95,13/07/2020 19:08:32,Female,18.0,Islamic Education,year 1,2.0,0,0,0,0,0,0
96,13/07/2020 19:56:49,Female,21.0,BCS,year 1,2.0,0,0,1,0,0,0
97,13/07/2020 21:21:42,Male,18.0,Engineering,Year 2,1.0,0,1,1,0,0,1
98,13/07/2020 21:22:56,Female,19.0,Nursing,Year 3,2.0,1,1,0,1,0,0
99,13/07/2020 21:23:57,Female,23.0,Pendidikan Islam,year 4,2.0,0,0,0,0,0,0
100,18/07/2020 20:16:21,Male,20.0,Biomedical science,Year 2,1.0,0,0,0,0,0,1

In [16]:
mental.isnull().sum()

Timestamp                                       0
Choose your gender                              0
Age                                             0
What is your course?                            0
Your current year of Study                      0
What is your CGPA?                              1
Marital status                                  0
Do you have Depression?                         0
Do you have Anxiety?                            0
Do you have Panic attack?                       0
Did you seek any specialist for a treatment?    0
Choose Your gender                              0
dtype: int64

In [17]:
mental.dtypes

Timestamp                                        object
Choose your gender                               object
Age                                             float64
What is your course?                             object
Your current year of Study                       object
What is your CGPA?                              float64
Marital status                                    int64
Do you have Depression?                           int64
Do you have Anxiety?                              int64
Do you have Panic attack?                         int64
Did you seek any specialist for a treatment?      int64
Choose Your gender                                int64
dtype: object